### ISSUE TITLE
Probably should have a `lib.rs`

### ISSUE THREAD

**Issue by AbhinavMir** [iFrostizz/murph#2]
I'm working on a project where I need Murph's capabilities, so writing a `lib.rs`, are the maintainers open to having it here canonically?

**Comment by franfrandev** [comment]
Sure, I can do that

**Comment by AbhinavMir** [comment]
Do you want me to take this up or is this something you'd want to do?

**Comment by franfrandev** [comment]
I'm alright doing it, gonna do it today 🙂

**Comment by franfrandev** [comment]
there you go: https://github.com/iFrostizz/murph/commit/ec870ebe7d172a3c31e8dfc8fe82b7f728e9203e

You can import murph using this:

```toml
# Cargo.toml
[package]
name = "mymurph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
murph = { path = "/home/franfran/Projects/own/murph" }
```

```rust
// main.rs
use murph::parser;

fn main() {
    let bytecode = String::from("6040");

    let parsed = parser::parse(bytecode, false);

    dbg!(&parsed);
}
```
